name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 12 Pro Max']
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean build -project CustomTextFields.xcodeproj -scheme CustomTextFields -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
         MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
      - name: Test
        run: |
          xcodebuild clean test -project CustomTextFields.xcodeproj -scheme CustomTextFieldsUITests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
         MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
