name: Swift

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max']
    steps:
      - name: Test
        run: |
          xcodebuild clean test -project GHFollowers.xcodeproj -scheme CustomTextFieldsUITests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
